name: Java CI

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        
      - name: Run Tests
        run: mvn test
